export const INITIAL_DEPARTMENTS = [
  {
    code: 'CSE',
    name: 'Computer Science & Engineering',
    description: 'Empowering future computing architects, AI researchers, and software engineers.',
    icon: 'Laptop',
    order: 1,
    isActive: true,
  },
  {
    code: 'IT',
    name: 'Information Technology',
    description: 'Pioneering cutting-edge cloud infrastructure, cybersecurity, and modern web solutions.',
    icon: 'Network',
    order: 2,
    isActive: true,
  },
  {
    code: 'EEE',
    name: 'Electrical & Electronics Engineering',
    description: 'Engineering resilient smart energy grids, power electronics, and sustainable drives.',
    icon: 'Zap',
    order: 3,
    isActive: true,
  },
  {
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    description: 'Transforming telecommunication, VLSI microelectronics, and embedded signal processing.',
    icon: 'Radio',
    order: 4,
    isActive: true,
  },
  {
    code: 'ME',
    name: 'Mechanical Engineering',
    description: 'Mastering thermal dynamics, robotic fabrication, CAD/CAM design, and aerospace mechanics.',
    icon: 'Cog',
    order: 5,
    isActive: true,
  },
  {
    code: 'RAI',
    name: 'Robotics & Artificial Intelligence',
    description: 'Advancing autonomous navigation, intelligent agents, humanoid kinesthetics, and computer vision.',
    icon: 'Bot',
    order: 6,
    isActive: true,
  },
];

export const INITIAL_SEMESTERS = [
  { code: 'S1', name: 'Semester 1', order: 1, isActive: true },
  { code: 'S2', name: 'Semester 2', order: 2, isActive: true },
  { code: 'S3', name: 'Semester 3', order: 3, isActive: true },
  { code: 'S4', name: 'Semester 4', order: 4, isActive: true },
  { code: 'S5', name: 'Semester 5', order: 5, isActive: true },
  { code: 'S6', name: 'Semester 6', order: 6, isActive: true },
  { code: 'S7', name: 'Semester 7', order: 7, isActive: true },
  { code: 'S8', name: 'Semester 8', order: 8, isActive: true },
];

export const INITIAL_ACADEMIC_YEARS = [
  { year: '2026-27', isCurrent: true, isActive: true },
  { year: '2025-26', isCurrent: false, isActive: true },
  { year: '2024-25', isCurrent: false, isActive: true },
  { year: '2023-24', isCurrent: false, isActive: true },
];

export const INITIAL_CATEGORIES = [
  { name: 'Class Notes', type: 'notes', slug: 'class-notes', isActive: true },
  { name: 'Unit Notes', type: 'notes', slug: 'unit-notes', isActive: true },
  { name: 'Study Material', type: 'notes', slug: 'study-material', isActive: true },
  { name: 'Assignments', type: 'notes', slug: 'assignments', isActive: true },
  { name: 'Lab Material', type: 'notes', slug: 'lab-material', isActive: true },
  { name: 'Question Bank', type: 'notes', slug: 'question-bank', isActive: true },
  { name: 'Syllabus', type: 'notes', slug: 'syllabus', isActive: true },
  { name: 'University Examination', type: 'question-paper', slug: 'university-exam', isActive: true },
  { name: 'Model Examination', type: 'question-paper', slug: 'model-exam', isActive: true },
  { name: 'Internal Examination', type: 'question-paper', slug: 'internal-exam', isActive: true },
  { name: 'Improvement Examination', type: 'question-paper', slug: 'improvement-exam', isActive: true },
];

export const INITIAL_SUBJECTS = [
  // CSE S1
  { name: 'Mathematics for Information Science-1', code: 'GAMAT101', department: 'CSE', semester: 'S1', description: 'Mathematics for Information Science - 1' },
  { name: 'Physics for Information Science', code: 'GAPHT121', department: 'CSE', semester: 'S1', description: 'Physics for Information Science' },
  { name: 'Engineering Graphics and Computer Aided Drawing', code: 'GMEST103', department: 'CSE', semester: 'S1', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Introduction to Electrical and Electronics Engineering', code: 'GXEST104', department: 'CSE', semester: 'S1', description: 'Introduction to Electrical and Electronics Engineering' },
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'CSE', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Basic Electrical and Electronics Engineering Workshop', code: 'GXESL106', department: 'CSE', semester: 'S1', description: 'Basic Electrical and Electronics Engineering Workshop' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'CSE', semester: 'S1', description: 'Life Skills and Professional Communication' },

  // IT S1
  { name: 'Mathematics', code: 'GAMAT101', department: 'IT', semester: 'S1', description: 'Calculus and Linear Algebra' },
  { name: 'Physics', code: 'GAPT121', department: 'IT', semester: 'S1', description: 'Engineering Physics' },
  { name: 'Engineering Graphics and computer aided drawing', code: 'GMEST103', department: 'IT', semester: 'S1', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Introduction to Electrical & Electronics Engineering', code: 'GXEST104', department: 'IT', semester: 'S1', description: 'Introduction to Electrical & Electronics Engineering' },
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'IT', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Life skill and professional communication', code: 'UCHUT128', department: 'IT', semester: 'S1', description: 'Life skill and professional communication' },
  { name: 'Basic Electrical & Electronics Workshop', code: 'GXESL106', department: 'IT', semester: 'S1', description: 'Basic Electrical & Electronics Workshop' },

  // CSE S2
  { name: 'Mathematics for Information Science - 2', code: 'GAMAT201', department: 'CSE', semester: 'S2', description: 'Mathematics for Information Science - 2' },
  { name: 'Chemistry for Information Science / Electrical Science', code: 'GXCYT122', department: 'CSE', semester: 'S2', description: 'Chemistry for Information Science / Electrical Science' },
  { name: 'Foundations of Computing: From Hardware Essentials to Web Design', code: 'GXEST203', department: 'CSE', semester: 'S2', description: 'Foundations of Computing: From Hardware Essentials to Web Design' },
  { name: 'Programming in C', code: 'GXEST204', department: 'CSE', semester: 'S2', description: 'Programming in C' },
  { name: 'Discrete Mathematics', code: 'PCCST205', department: 'CSE', semester: 'S2', description: 'Discrete Mathematics' },
  { name: 'Engineering Entrepreneurship & IPR', code: 'UCEST206', department: 'CSE', semester: 'S2', description: 'Engineering Entrepreneurship & IPR' },
  { name: 'IT Workshop', code: 'GXESL208', department: 'CSE', semester: 'S2', description: 'IT Workshop' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'CSE', semester: 'S2', description: 'Health and Wellness' },
  { name: 'Skill Enhancement Course: Digital 101', code: 'UCSEM129', department: 'CSE', semester: 'S2', description: 'Skill Enhancement Course: Digital 101' },

  // IT S2
  { name: 'Chemistry for Information Science / Electrical Science', code: 'GXCYT122', department: 'IT', semester: 'S2', description: 'Chemistry for Information Science / Electrical Science' },
  { name: 'Discrete Mathematical Structures', code: 'PCITT205', department: 'IT', semester: 'S2', description: 'Discrete Mathematical Structures' },
  { name: 'Engineering Entrepreneurship & IPR', code: 'UCEST206', department: 'IT', semester: 'S2', description: 'Engineering Entrepreneurship & IPR' },
  { name: 'Foundations of Computing: From Hardware Essentials to Web Design', code: 'GXEST203', department: 'IT', semester: 'S2', description: 'Foundations of Computing: From Hardware Essentials to Web Design' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'IT', semester: 'S2', description: 'Health and Wellness' },
  { name: 'IT Workshop', code: 'GXESL208', department: 'IT', semester: 'S2', description: 'IT Workshop' },
  { name: 'Mathematics for Information Science – 2', code: 'GAMAT201', department: 'IT', semester: 'S2', description: 'Mathematics for Information Science – 2' },
  { name: 'Programming in C', code: 'GXEST204', department: 'IT', semester: 'S2', description: 'Programming in C' },
  { name: 'Skill Enhancement Course: Digital 101', code: 'UCSEM129', department: 'IT', semester: 'S2', description: 'Skill Enhancement Course: Digital 101' },

  // IT S3
  { name: 'Mathematics for Information Science-3', code: 'GAMAT301', department: 'IT', semester: 'S3', description: 'Mathematics for Information Science-3' },
  { name: 'Computer Organisation and Architecture', code: 'PCITT302', department: 'IT', semester: 'S3', description: 'Computer Organisation and Architecture' },
  { name: 'Data Structures', code: 'PCITT303', department: 'IT', semester: 'S3', description: 'Data Structures' },
  { name: 'Database Management System', code: 'PBITT304', department: 'IT', semester: 'S3', description: 'Database Management System' },
  { name: 'Digital Electronics & Logic Design', code: 'GAEST305', department: 'IT', semester: 'S3', description: 'Digital Electronics & Logic Design' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'IT', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },

  // IT S4
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'IT', semester: 'S4', description: 'Economics for Engineers' },
  { name: 'Mathematics for Information Science-IV', code: 'GAMAT401', department: 'IT', semester: 'S4', description: 'Mathematics for Information Science-IV' },
  { name: 'Computer Networks', code: 'PCITT402', department: 'IT', semester: 'S4', description: 'Computer Networks' },
  { name: 'Data Science', code: 'PBITT404', department: 'IT', semester: 'S4', description: 'Data Science' },
  { name: 'Operating Systems', code: 'PCITT403', department: 'IT', semester: 'S4', description: 'Operating Systems' },
  { name: 'Computer Networks Lab', code: 'PCITL407', department: 'IT', semester: 'S4', description: 'Computer Networks Lab' },
  { name: 'Operating Systems Lab', code: 'PCITL408', department: 'IT', semester: 'S4', description: 'Operating Systems Lab' },
  { name: 'Data Communication and Networking', code: 'PEITT412', department: 'IT', semester: 'S4', description: 'Data Communication and Networking' },

  // IT S5
  { name: 'Machine Learning', code: 'PCITT501', department: 'IT', semester: 'S5', description: 'Machine Learning' },
  { name: 'Algorithm Analysis and Design', code: 'PCITT502', department: 'IT', semester: 'S5', description: 'Algorithm Analysis and Design' },
  { name: 'Software Engineering', code: 'PCITT503', department: 'IT', semester: 'S5', description: 'Software Engineering' },
  { name: 'Web Application Development', code: 'PBITT504', department: 'IT', semester: 'S5', description: 'Web Application Development' },
  { name: 'Machine Learning Lab', code: 'PCITL507', department: 'IT', semester: 'S5', description: 'Machine Learning Lab' },
  { name: 'Algorithm Analysis and Design Lab', code: 'PCITL508', department: 'IT', semester: 'S5', description: 'Algorithm Analysis and Design Lab' },
  { name: 'Cloud Computing', code: 'PEITT523', department: 'IT', semester: 'S5', description: 'Programme Elective 1A' },
  { name: 'Internetworking with TCP/IP', code: 'PEITT522', department: 'IT', semester: 'S5', description: 'Programme Elective 1B' },
  { name: 'Minor Course: Software Engineering', code: 'MNITT501', department: 'IT', semester: 'S5', description: 'Minor Course: Software Engineering' },
  { name: 'Honor: Security and Ethical Hacking', code: 'HNITT501', department: 'IT', semester: 'S5', description: 'Honor: Security and Ethical Hacking' },

  // CSE S3
  { name: 'Mathematics for Computer and Information Science-3', code: 'GAMAT301', department: 'CSE', semester: 'S3', description: 'Mathematics for Computer and Information Science - 3' },
  { name: 'Theory of Computation', code: 'PCCST302', department: 'CSE', semester: 'S3', description: 'Theory of Computation' },
  { name: 'Data Structures and Algorithms', code: 'PCCST303', department: 'CSE', semester: 'S3', description: 'Data Structures and Algorithms' },
  { name: 'Object Oriented Programming', code: 'PBCST304', department: 'CSE', semester: 'S3', description: 'Object Oriented Programming' },
  { name: 'Digital Electronics and Logic Design', code: 'GAEST305', department: 'CSE', semester: 'S3', description: 'Digital Electronics and Logic Design' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'CSE', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Data Structures Lab', code: 'PCCSL307', department: 'CSE', semester: 'S3', description: 'Data Structures Lab' },
  { name: 'Digital Lab', code: 'PCCSL308', department: 'CSE', semester: 'S3', description: 'Digital Lab' },

  // CSE S4
  { name: 'Mathematics for Computer and Information Science-4', code: 'GAMAT401', department: 'CSE', semester: 'S4', description: 'Mathematics for Computer and Information Science - 4' },
  { name: 'Database Management Systems', code: 'PCCST402', department: 'CSE', semester: 'S4', description: 'Database Management Systems' },
  { name: 'Operating Systems', code: 'PCCST403', department: 'CSE', semester: 'S4', description: 'Operating Systems' },
  { name: 'Computer Organization and Architecture', code: 'PBCST404', department: 'CSE', semester: 'S4', description: 'Computer Organization and Architecture' },
  { name: 'Software Engineering', code: 'PECST411', department: 'CSE', semester: 'S4', description: 'Software Engineering' },
  { name: 'Cyber Ethics, Privacy and Legal Issues', code: 'PECST419', department: 'CSE', semester: 'S4', description: 'Cyber Ethics, Privacy and Legal Issues' },
  { name: 'Operating Systems Lab', code: 'PCCSL407', department: 'CSE', semester: 'S4', description: 'Operating Systems Lab' },
  { name: 'DBMS Lab', code: 'PCCSL408', department: 'CSE', semester: 'S4', description: 'Database Management Systems Lab' },

  // CSE S5
  { name: 'Computer Networks', code: 'PCCST501', department: 'CSE', semester: 'S5', description: 'Computer Networks' },
  { name: 'Design and Analysis of Algorithms', code: 'PCCST502', department: 'CSE', semester: 'S5', description: 'Design and Analysis of Algorithms' },
  { name: 'Machine Learning', code: 'PCCST503', department: 'CSE', semester: 'S5', description: 'Machine Learning' },
  { name: 'Microcontrollers', code: 'PBCST504', department: 'CSE', semester: 'S5', description: 'Microcontrollers' },
  { name: 'Software Project Management', code: 'PECST521', department: 'CSE', semester: 'S5', description: 'Software Project Management' },
  { name: 'Data Analytics', code: 'PECST523', department: 'CSE', semester: 'S5', description: 'Data Analytics' },
  { name: 'Computer Graphics and Multimedia', code: 'PECST527', department: 'CSE', semester: 'S5', description: 'Computer Graphics and Multimedia' },
  { name: 'Networks Lab', code: 'PCCSL507', department: 'CSE', semester: 'S5', description: 'Networks Lab' },
  { name: 'Machine Learning Lab', code: 'PCCSL508', department: 'CSE', semester: 'S5', description: 'Machine Learning Lab' },

  // ECE S1
  { name: 'Mathematics for Electrical Science and Physical Science - 1', code: 'GYMAT101', department: 'ECE', semester: 'S1', description: 'Mathematics for Electrical Science and Physical Science - 1' },
  { name: 'Physics for Electrical Science', code: 'GBPHT121', department: 'ECE', semester: 'S1', description: 'Physics for Electrical Science' },
  { name: 'Chemistry for Information Science & Electrical Science', code: 'GXCYT122', department: 'ECE', semester: 'S1', description: 'Chemistry for Information Science & Electrical Science' },
  { name: 'Engineering Graphics and Computer Aided Drawing', code: 'GMEST103', department: 'ECE', semester: 'S1', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Introduction to Electrical and Electronics Engineering', code: 'GXEST104', department: 'ECE', semester: 'S1', description: 'Introduction to Electrical and Electronics Engineering' },
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'ECE', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Health and Wellness', code: 'UCPWT127', department: 'ECE', semester: 'S1', description: 'Health and Wellness' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'ECE', semester: 'S1', description: 'Life Skills and Professional Communication' },
  { name: 'Basic Electrical and Electronics Engineering Workshop', code: 'GXESL106', department: 'ECE', semester: 'S1', description: 'Basic Electrical and Electronics Engineering Workshop' },

  // ECE S2
  { name: 'Mathematics for Electrical Science and Physical Science - 2', code: 'GYMAT201', department: 'ECE', semester: 'S2', description: 'Mathematics for Electrical Science and Physical Science - 2' },
  { name: 'Foundations of Computing: From Hardware Essentials to Web Design', code: 'GXEST203', department: 'ECE', semester: 'S2', description: 'Foundations of Computing: From Hardware Essentials to Web Design' },
  { name: 'Programming in C', code: 'GXEST204', department: 'ECE', semester: 'S2', description: 'Programming in C' },
  { name: 'Engineering Entrepreneurship and IPR', code: 'UCEST206', department: 'ECE', semester: 'S2', description: 'Engineering Entrepreneurship and IPR' },
  { name: 'IT Workshop', code: 'GXESL208', department: 'ECE', semester: 'S2', description: 'IT Workshop' },
  { name: 'Network Theory', code: 'PCECT205', department: 'ECE', semester: 'S2', description: 'Network Theory' },
  { name: 'Logic Circuit Design', code: 'PCEIT205', department: 'ECE', semester: 'S2', description: 'Logic Circuit Design' },
  { name: 'Analog Electronics Circuits', code: 'PCEOT205', department: 'ECE', semester: 'S2', description: 'Analog Electronics Circuits' },

  // ECE S3
  { name: 'Mathematics for Electrical Science and Physical Science – 3', code: 'GYMAT301', department: 'ECE', semester: 'S3', description: 'Mathematics for Electrical Science and Physical Science - 3' },
  { name: 'Solid State Devices', code: 'PCECT302', department: 'ECE', semester: 'S3', description: 'Solid State Devices' },
  { name: 'Analog Circuits', code: 'PCECT303', department: 'ECE', semester: 'S3', description: 'Analog Circuits' },
  { name: 'Logic Circuit Design', code: 'PBECT304', department: 'ECE', semester: 'S3', description: 'Logic Circuit Design' },
  { name: 'Introduction to Artificial Intelligence and Data Science', code: 'GNEST305', department: 'ECE', semester: 'S3', description: 'Introduction to Artificial Intelligence and Data Science' },
  { name: 'Engineering Economics', code: 'UCHUT346', department: 'ECE', semester: 'S3', description: 'Engineering Economics' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'ECE', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Analog Circuits Lab', code: 'PCECL307', department: 'ECE', semester: 'S3', description: 'Analog Circuits Lab' },
  { name: 'Logic Circuit Design Laboratory', code: 'PCECL308', department: 'ECE', semester: 'S3', description: 'Logic Circuit Design Laboratory' },

  // ECE S4
  { name: 'Mathematics for Electrical Science – 4', code: 'GBMAT401', department: 'ECE', semester: 'S4', description: 'Mathematics for Electrical Science - 4' },
  { name: 'Signals and Systems', code: 'PCECT402', department: 'ECE', semester: 'S4', description: 'Signals and Systems' },
  { name: 'Linear Integrated Circuits', code: 'PCECT403', department: 'ECE', semester: 'S4', description: 'Linear Integrated Circuits' },
  { name: 'Microcontrollers', code: 'PBECT404', department: 'ECE', semester: 'S4', description: 'Microcontrollers' },
  { name: 'Instrumentation', code: 'PEECT411', department: 'ECE', semester: 'S4', description: 'Instrumentation' },
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'ECE', semester: 'S4', description: 'Economics for Engineers' },
  { name: 'Linear Integrated Circuits Lab', code: 'PCECL407', department: 'ECE', semester: 'S4', description: 'Linear Integrated Circuits Lab' },
  { name: 'Microcontroller Lab', code: 'PCECL408', department: 'ECE', semester: 'S4', description: 'Microcontroller Lab' },

  // ECE S5
  { name: 'Electromagnetics', code: 'PCECT501', department: 'ECE', semester: 'S5', description: 'Electromagnetics' },
  { name: 'Analog and Digital Communication', code: 'PCECT502', department: 'ECE', semester: 'S5', description: 'Analog and Digital Communication' },
  { name: 'Control Systems', code: 'PCECT503', department: 'ECE', semester: 'S5', description: 'Control Systems' },
  { name: 'Digital Signal Processing', code: 'PBECT504', department: 'ECE', semester: 'S5', description: 'Digital Signal Processing' },
  { name: 'Sensors and Actuators', code: 'PEECT523', department: 'ECE', semester: 'S5', description: 'Sensors and Actuators' },
  { name: 'Biomedical Engineering', code: 'PEECT521', department: 'ECE', semester: 'S5', description: 'Biomedical Engineering' },
  { name: 'Digital Signal Processing Lab', code: 'PBECL507', department: 'ECE', semester: 'S5', description: 'Digital Signal Processing Lab' },
  { name: 'Communication Lab I', code: 'PCECL508', department: 'ECE', semester: 'S5', description: 'Communication Lab I' },

  // EEE S1
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'EEE', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Basic Electrical and Electronics Engineering Workshop', code: 'GXESL106', department: 'EEE', semester: 'S1', description: 'Basic Electrical and Electronics Engineering Workshop' },
  { name: 'Chemistry for Information Science / Electrical Science', code: 'GXCYT122', department: 'EEE', semester: 'S1', description: 'Chemistry for Information Science / Electrical Science' },
  { name: 'Engineering Graphics and Computer Aided Drawing', code: 'GMEST103', department: 'EEE', semester: 'S1', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'EEE', semester: 'S1', description: 'Health and Wellness' },
  { name: 'Introduction to Electrical & Electronics Engineering', code: 'GXEST104', department: 'EEE', semester: 'S1', description: 'Introduction to Electrical & Electronics Engineering' },
  { name: 'Mathematics for Electrical Science-1 / Physical Science-1', code: 'GYMAT101', department: 'EEE', semester: 'S1', description: 'Mathematics for Electrical Science-1 / Physical Science-1' },

  // EEE S2
  { name: 'Engineering Entrepreneurship & IPR', code: 'UCEST206', department: 'EEE', semester: 'S2', description: 'Engineering Entrepreneurship & IPR' },
  { name: 'Engineering Mechanics', code: 'GBEST213', department: 'EEE', semester: 'S2', description: 'Engineering Mechanics' },
  { name: 'IT Workshop', code: 'GXESL208', department: 'EEE', semester: 'S2', description: 'IT Workshop' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'EEE', semester: 'S2', description: 'Life Skills and Professional Communication' },
  { name: 'Mathematics for Electrical Science-2 / Physical Science-2', code: 'GYMAT201', department: 'EEE', semester: 'S2', description: 'Mathematics for Electrical Science-2 / Physical Science-2' },
  { name: 'Measurements and Instrumentation', code: 'PCEET205', department: 'EEE', semester: 'S2', description: 'Measurements and Instrumentation' },
  { name: 'Physics for Electrical Science', code: 'GBPHT121', department: 'EEE', semester: 'S2', description: 'Physics for Electrical Science' },
  { name: 'Programming in C', code: 'GXEST204', department: 'EEE', semester: 'S2', description: 'Programming in C' },
  { name: 'Skill Enhancement Course: Digital 101', code: 'UCSEM129', department: 'EEE', semester: 'S2', description: 'Skill Enhancement Course: Digital 101' },

  // EEE S3
  { name: 'Analog Electronics', code: 'PBEET304', department: 'EEE', semester: 'S3', description: 'Analog Electronics' },
  { name: 'Analog Electronics Lab', code: 'PCEEL308', department: 'EEE', semester: 'S3', description: 'Analog Electronics Lab' },
  { name: 'Circuits and Measurements Lab', code: 'PCEEL307', department: 'EEE', semester: 'S3', description: 'Circuits and Measurements Lab' },
  { name: 'Circuits and Networks', code: 'PCEET302', department: 'EEE', semester: 'S3', description: 'Circuits and Networks' },
  { name: 'DC Machines and Transformers', code: 'PCEET303', department: 'EEE', semester: 'S3', description: 'DC Machines and Transformers' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'EEE', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Introduction to Artificial Intelligence and Data Science', code: 'GNEST305', department: 'EEE', semester: 'S3', description: 'Introduction to Artificial Intelligence and Data Science' },
  { name: 'Mathematics for Physical Science-3 / Electrical Science-3', code: 'GYMAT301', department: 'EEE', semester: 'S3', description: 'Mathematics for Physical Science-3 / Electrical Science-3' },

  // EEE S4
  { name: 'DC Machines and Transformers Lab', code: 'PCEEL407', department: 'EEE', semester: 'S4', description: 'DC Machines and Transformers Lab' },
  { name: 'Digital Electronics', code: 'PBEET404', department: 'EEE', semester: 'S4', description: 'Digital Electronics' },
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'EEE', semester: 'S4', description: 'Economics for Engineers' },
  { name: 'Electronic Instrumentation', code: 'PEEET411', department: 'EEE', semester: 'S4', description: 'Electronic Instrumentation' },
  { name: 'Mathematics for Electrical Science-4', code: 'GBMAT401', department: 'EEE', semester: 'S4', description: 'Mathematics for Electrical Science-4' },
  { name: 'Power Electronics and Drives', code: 'PCEET403', department: 'EEE', semester: 'S4', description: 'Power Electronics and Drives' },
  { name: 'Power Electronics and Drives Lab', code: 'PCEEL408', department: 'EEE', semester: 'S4', description: 'Power Electronics and Drives Lab' },
  { name: 'Synchronous and Induction Machines', code: 'PCEET402', department: 'EEE', semester: 'S4', description: 'Synchronous and Induction Machines' },

  // EEE S5
  { name: 'Power Generation Transmission and Protection', code: 'PCEET501', department: 'EEE', semester: 'S5', description: 'Power Generation Transmission and Protection' },
  { name: 'Electromagnetic Theory', code: 'PCEET502', department: 'EEE', semester: 'S5', description: 'Electromagnetic Theory' },
  { name: 'Signals and Systems', code: 'PCEET503', department: 'EEE', semester: 'S5', description: 'Signals and Systems' },
  { name: 'Microprocessors and Embedded Systems', code: 'PBEET504', department: 'EEE', semester: 'S5', description: 'Microprocessors and Embedded Systems' },
  { name: 'Energy Storage Systems', code: 'PEEET521', department: 'EEE', semester: 'S5', description: 'Energy Storage Systems' },
  { name: 'Electric Vehicles', code: 'PEEET522', department: 'EEE', semester: 'S5', description: 'Electric Vehicles' },

  // ME S1
  { name: 'Mathematics for Electrical Science-1 / Physical Science-1', code: 'GYMAT101', department: 'ME', semester: 'S1', description: 'Mathematics for Electrical Science-1 / Physical Science-1' },
  { name: 'Physics for Physical Science / Life Science', code: 'GZPHT121', department: 'ME', semester: 'S1', description: 'Physics for Physical Science / Life Science' },
  { name: 'Engineering Mechanics', code: 'GCEST103', department: 'ME', semester: 'S1', description: 'Engineering Mechanics' },
  { name: 'Introduction to Mechanical Engineering & Civil Engineering', code: 'GCEST104', department: 'ME', semester: 'S1', description: 'Introduction to Mechanical Engineering & Civil Engineering' },
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'ME', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Engineering Workshop', code: 'GCESL106', department: 'ME', semester: 'S1', description: 'Engineering Workshop' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'ME', semester: 'S1', description: 'Life Skills and Professional Communication' },

  // ME S2
  { name: 'Mathematics for Electrical Science-2 / Physical Science-2', code: 'GYMAT201', department: 'ME', semester: 'S2', description: 'Mathematics for Electrical Science-2 / Physical Science-2' },
  { name: 'Chemistry for Physical Science', code: 'GCCYT122', department: 'ME', semester: 'S2', description: 'Chemistry for Physical Science' },
  { name: 'Engineering Graphics and Computer Aided Drawing', code: 'GCEST203', department: 'ME', semester: 'S2', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Basic Electrical & Electronics Engineering', code: 'GZEST204', department: 'ME', semester: 'S2', description: 'Basic Electrical & Electronics Engineering' },
  { name: 'Material Science and Engineering', code: 'PCMET205', department: 'ME', semester: 'S2', description: 'Material Science and Engineering' },
  { name: 'Engineering Entrepreneurship & IPR', code: 'UCEST206', department: 'ME', semester: 'S2', description: 'Engineering Entrepreneurship & IPR' },
  { name: 'Basic Electrical and Electronics Engineering Workshop', code: 'GZESL208', department: 'ME', semester: 'S2', description: 'Basic Electrical and Electronics Engineering Workshop' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'ME', semester: 'S2', description: 'Health and Wellness' },

  // ME S3
  { name: 'Mathematics for Physical Science-3 / Electrical Science-3', code: 'GYMAT301', department: 'ME', semester: 'S3', description: 'Mathematics for Physical Science-3 / Electrical Science-3' },
  { name: 'Mechanics of Solids', code: 'PCMET302', department: 'ME', semester: 'S3', description: 'Mechanics of Solids' },
  { name: 'Fluid Mechanics and Machinery', code: 'PCMET303', department: 'ME', semester: 'S3', description: 'Fluid Mechanics and Machinery' },
  { name: 'Manufacturing Processes', code: 'PBMET304', department: 'ME', semester: 'S3', description: 'Manufacturing Processes' },
  { name: 'Introduction to Artificial Intelligence and Data Science', code: 'GNEST305', department: 'ME', semester: 'S3', description: 'Introduction to Artificial Intelligence and Data Science' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'ME', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Computer Aided Machine Drawing & Modelling', code: 'PCMEL307', department: 'ME', semester: 'S3', description: 'Computer Aided Machine Drawing & Modelling' },
  { name: 'Materials Testing Lab', code: 'PCMEL308', department: 'ME', semester: 'S3', description: 'Materials Testing Lab' },

  // ME S4
  { name: 'Mathematics for Physical Science-4', code: 'GCMAT401', department: 'ME', semester: 'S4', description: 'Mathematics for Physical Science-4' },
  { name: 'Machine Tools and Metrology', code: 'PCMET402', department: 'ME', semester: 'S4', description: 'Machine Tools and Metrology' },
  { name: 'Engineering Thermodynamics', code: 'PCMET403', department: 'ME', semester: 'S4', description: 'Engineering Thermodynamics' },
  { name: 'Mechanics of Machinery', code: 'PBMET404', department: 'ME', semester: 'S4', description: 'Mechanics of Machinery' },
  { name: 'Advanced Metal Joining Techniques', code: 'PEMET416', department: 'ME', semester: 'S4', description: 'Advanced Metal Joining Techniques' },
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'ME', semester: 'S4', description: 'Economics for Engineers' },
  { name: 'Fluid Mechanics and Hydraulic Machines Lab', code: 'PCMEL407', department: 'ME', semester: 'S4', description: 'Fluid Mechanics and Hydraulic Machines Lab' },
  { name: 'Manufacturing Technology Lab', code: 'PCMEL408', department: 'ME', semester: 'S4', description: 'Manufacturing Technology Lab' },

  // ME S5
  { name: 'Dynamics of Machinery', code: 'PCMET501', department: 'ME', semester: 'S5', description: 'Dynamics of Machinery' },
  { name: 'Advanced Manufacturing Engineering', code: 'PCMET502', department: 'ME', semester: 'S5', description: 'Advanced Manufacturing Engineering' },
  { name: 'Heat and Mass Transfer', code: 'PCMET503', department: 'ME', semester: 'S5', description: 'Heat and Mass Transfer' },
  { name: 'Management for Engineers', code: 'PBMET504', department: 'ME', semester: 'S5', description: 'Management for Engineers' },
  { name: 'Thermal Engineering Lab 1', code: 'PCMEL507', department: 'ME', semester: 'S5', description: 'Thermal Engineering Lab 1' },
  { name: 'Mechanical Engineering Lab', code: 'PCMEL508', department: 'ME', semester: 'S5', description: 'Mechanical Engineering Lab' },
  { name: 'Additive Manufacturing', code: 'PEMET524', department: 'ME', semester: 'S5', description: 'Additive Manufacturing' },
  { name: 'Operations Research', code: 'PEMET528', department: 'ME', semester: 'S5', description: 'Operations Research' },

  // RAI S1
  { name: 'Mathematics for Electrical Science-1', code: 'GYMAT101', department: 'RAI', semester: 'S1', description: 'Mathematics for Electrical Science-1' },
  { name: 'Physics for Electrical Science', code: 'GBPHT121', department: 'RAI', semester: 'S1', description: 'Physics for Electrical Science' },
  { name: 'Chemistry for Electrical Science', code: 'GXCYT122', department: 'RAI', semester: 'S1', description: 'Chemistry for Electrical Science' },
  { name: 'Engineering Graphics and Computer Aided Drawing', code: 'GMEST103', department: 'RAI', semester: 'S1', description: 'Engineering Graphics and Computer Aided Drawing' },
  { name: 'Introduction to Electrical & Electronics Engineering', code: 'GXEST104', department: 'RAI', semester: 'S1', description: 'Introduction to Electrical & Electronics Engineering' },
  { name: 'Algorithmic Thinking with Python', code: 'UCEST105', department: 'RAI', semester: 'S1', description: 'Algorithmic Thinking with Python' },
  { name: 'Basic Electrical and Electronics Engineering Workshop', code: 'GXESL106', department: 'RAI', semester: 'S1', description: 'Basic Electrical and Electronics Engineering Workshop' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'RAI', semester: 'S1', description: 'Health and Wellness' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'RAI', semester: 'S1', description: 'Life Skills and Professional Communication' },
  { name: 'Skill Enhancement Course: Digital 101', code: 'UCSEM129', department: 'RAI', semester: 'S1', description: 'Skill Enhancement Course: Digital 101 (30 Hours, NASSCOM)' },

  // RAI S2
  { name: 'Mathematics for Electrical Science-2', code: 'GYMAT201', department: 'RAI', semester: 'S2', description: 'Mathematics for Electrical Science-2' },
  { name: 'Physics for Engineers', code: 'GBPHT121', department: 'RAI', semester: 'S2', description: 'Physics for Engineers' },
  { name: 'Chemistry for Engineers', code: 'GXCYT122', department: 'RAI', semester: 'S2', description: 'Chemistry for Engineers' },
  { name: 'Engineering Mechanics', code: 'GBEST213', department: 'RAI', semester: 'S2', description: 'Engineering Mechanics' },
  { name: 'Programming in C', code: 'GXEST204', department: 'RAI', semester: 'S2', description: 'Programming in C' },
  { name: 'Sensors and Actuators for Robotics', code: 'PCRAT205', department: 'RAI', semester: 'S2', description: 'Sensors and Actuators for Robotics' },
  { name: 'Engineering Entrepreneurship & IPR', code: 'UCEST206', department: 'RAI', semester: 'S2', description: 'Engineering Entrepreneurship & IPR' },
  { name: 'Health and Wellness', code: 'UCHWT127', department: 'RAI', semester: 'S2', description: 'Health and Wellness' },
  { name: 'Life Skills and Professional Communication', code: 'UCHUT128', department: 'RAI', semester: 'S2', description: 'Life Skills and Professional Communication' },
  { name: 'IT Workshop', code: 'GXESL208', department: 'RAI', semester: 'S2', description: 'IT Workshop' },
  { name: 'Skill Enhancement Course: Digital 101', code: 'UCSEM129', department: 'RAI', semester: 'S2', description: 'Skill Enhancement Course: Digital 101 (30 Hours, NASSCOM)' },

  // RAI S3
  { name: 'Mathematics for Electrical Science-3', code: 'GYMAT301', department: 'RAI', semester: 'S3', description: 'Mathematics for Electrical Science-3' },
  { name: 'Microcontrollers and Embedded Systems', code: 'PCRAT302', department: 'RAI', semester: 'S3', description: 'Microcontrollers and Embedded Systems' },
  { name: 'Robotic Manipulators and Workcell Design', code: 'PCRAT303', department: 'RAI', semester: 'S3', description: 'Robotic Manipulators and Workcell Design' },
  { name: 'Analog and Digital Electronics', code: 'PBRAT304', department: 'RAI', semester: 'S3', description: 'Analog and Digital Electronics' },
  { name: 'Introduction to Artificial Intelligence and Data Science', code: 'GNEST305', department: 'RAI', semester: 'S3', description: 'Introduction to Artificial Intelligence and Data Science (Group Specific Syllabus)' },
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'RAI', semester: 'S3', description: 'Economics for Engineers' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'RAI', semester: 'S3', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Analog and Digital Electronics Lab', code: 'PCRAL307', department: 'RAI', semester: 'S3', description: 'Analog and Digital Electronics Lab' },
  { name: 'Microcontrollers and Embedded Systems Lab', code: 'PCRAL308', department: 'RAI', semester: 'S3', description: 'Microcontrollers and Embedded Systems Lab' },
  { name: 'Remedial / Minor Course', code: 'VAC', department: 'RAI', semester: 'S3', description: 'Remedial / Minor Course' },

  // RAI S4
  { name: 'Mathematics for Electrical Science-4', code: 'GBMAT401', department: 'RAI', semester: 'S4', description: 'Mathematics for Electrical Science-4' },
  { name: 'Signal Processing for Robotics', code: 'PCRAT402', department: 'RAI', semester: 'S4', description: 'Signal Processing for Robotics' },
  { name: 'Kinematics of Machinery', code: 'PCRAT403', department: 'RAI', semester: 'S4', description: 'Kinematics of Machinery' },
  { name: 'Artificial Intelligence & Machine Learning', code: 'PBRAT404', department: 'RAI', semester: 'S4', description: 'Artificial Intelligence & Machine Learning' },
  { name: 'Program Elective 1 (PE-1)', code: 'PERAT41N', department: 'RAI', semester: 'S4', description: 'Program Elective 1' },
  { name: 'Economics for Engineers', code: 'UCHUT346', department: 'RAI', semester: 'S4', description: 'Economics for Engineers' },
  { name: 'Engineering Ethics and Sustainable Development', code: 'UCHUT347', department: 'RAI', semester: 'S4', description: 'Engineering Ethics and Sustainable Development' },
  { name: 'Computer Aided Modeling and Simulation of Mechanical Systems', code: 'PCRAL407', department: 'RAI', semester: 'S4', description: 'Computer Aided Modeling and Simulation of Mechanical Systems' },
  { name: 'Artificial Intelligence & Machine Learning Lab', code: 'PCRAL408', department: 'RAI', semester: 'S4', description: 'Artificial Intelligence & Machine Learning Lab' },
  { name: 'Remedial / Minor / Honours Course', code: 'VAC', department: 'RAI', semester: 'S4', description: 'Remedial / Minor / Honours Course' },
];

export const INITIAL_MATERIALS = [
  // Notes for DBMS (CSE S6)
  {
    title: 'Unit 1: DBMS Introduction & ER Modeling',
    description: 'Complete lecture notes covering file systems vs DBMS, 3-tier architecture, data independence, and ER diagrams with real examples.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'Unit Notes',
    unitNumber: 1,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_dbms_unit1_geci/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_dbms_unit1_geci/view',
    fileName: 'DBMS_Unit1_Introduction_ER.pdf',
    fileSize: 2450000,
    downloadCount: 342,
    isPublished: true,
  },
  {
    title: 'Unit 2: Relational Model & Relational Algebra',
    description: 'Detailed study material on Codd rules, relational constraints, tuple relational calculus, and algebraic query optimization.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'Unit Notes',
    unitNumber: 2,
    fileSource: 'cloudinary',
    fileUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_unit2.pdf',
    cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_unit2.pdf',
    cloudinaryPublicId: 'sfi-geci/notes/CSE/S6/dbms_unit2',
    fileName: 'DBMS_Unit2_Relational_Model.pdf',
    fileSize: 3120000,
    downloadCount: 289,
    isPublished: true,
  },
  {
    title: 'Unit 3: Structured Query Language (SQL) Handbook',
    description: 'DDL, DML, DCL, complex nested subqueries, views, triggers, assertions, and PL/SQL stored procedures with sample queries.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'Class Notes',
    unitNumber: 3,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_dbms_unit3_sql/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_dbms_unit3_sql/view',
    fileName: 'DBMS_Unit3_SQL_Mastery.pdf',
    fileSize: 4500000,
    downloadCount: 512,
    isPublished: true,
  },
  {
    title: 'Unit 4: Functional Dependencies & Normalization',
    description: 'Step-by-step algorithms for 1NF, 2NF, 3NF, BCNF, lossless join decomposition, and dependency preservation proofs.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'Study Material',
    unitNumber: 4,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_dbms_unit4_normalization/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_dbms_unit4_normalization/view',
    fileName: 'DBMS_Unit4_Normalization.pdf',
    fileSize: 1890000,
    downloadCount: 420,
    isPublished: true,
  },
  {
    title: 'Unit 5: Transaction Processing, Concurrency & Recovery',
    description: 'ACID properties, serializability schedules, two-phase locking (2PL), deadlock prevention, timestamp ordering, and WAL recovery.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'Unit Notes',
    unitNumber: 5,
    fileSource: 'cloudinary',
    fileUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_unit5.pdf',
    cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_unit5.pdf',
    cloudinaryPublicId: 'sfi-geci/notes/CSE/S6/dbms_unit5',
    fileName: 'DBMS_Unit5_Transactions_Concurrency.pdf',
    fileSize: 2780000,
    downloadCount: 367,
    isPublished: true,
  },

  // Notes for Compiler Design (CSE S6)
  {
    title: 'Unit 1 & 2: Lexical Analysis & Syntax Analysis',
    description: 'Complete notes on Lex tools, regular expressions to DFA, top-down LL(1) parsing, and bottom-up LR/LALR parsing tables.',
    type: 'notes',
    department: 'CSE',
    semester: 'S6',
    subject: 'Compiler Design',
    academicYear: '2026-27',
    category: 'Class Notes',
    unitNumber: 1,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_cd_unit1/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_cd_unit1/view',
    fileName: 'Compiler_Design_Lexical_Parsing.pdf',
    fileSize: 3400000,
    downloadCount: 215,
    isPublished: true,
  },

  // Question Papers for DBMS (CSE S6)
  {
    title: '2026 KTU Regular University Examination Question Paper',
    description: 'Full official KTU question paper with answer scheme key hints and marking distribution.',
    type: 'question-paper',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2026-27',
    category: 'University Examination',
    examYear: 2026,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2026/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2026/view',
    fileName: 'KTU_DBMS_May2026_QuestionPaper.pdf',
    fileSize: 1200000,
    downloadCount: 680,
    isPublished: true,
  },
  {
    title: '2025 KTU Regular & Supplementary Examination Question Paper',
    description: 'Official University question paper covering BCNF, Relational Algebra queries, and 2PL locking protocols.',
    type: 'question-paper',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2024-25',
    category: 'University Examination',
    examYear: 2025,
    fileSource: 'cloudinary',
    fileUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_qp2025.pdf',
    cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1689234857/sample_dbms_qp2025.pdf',
    cloudinaryPublicId: 'sfi-geci/question-papers/CSE/S6/dbms_2025',
    fileName: 'KTU_DBMS_June2025_QP.pdf',
    fileSize: 980000,
    downloadCount: 840,
    isPublished: true,
  },
  {
    title: '2024 KTU Regular University Examination Question Paper',
    description: 'Complete KTU S6 B.Tech question paper for DBMS CS302.',
    type: 'question-paper',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2023-24',
    category: 'University Examination',
    examYear: 2024,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2024/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2024/view',
    fileName: 'KTU_DBMS_May2024_QP.pdf',
    fileSize: 1100000,
    downloadCount: 710,
    isPublished: true,
  },
  {
    title: '2023 KTU University Examination Question Paper',
    description: 'Previous year question paper with detailed schema diagrams and normalization questions.',
    type: 'question-paper',
    department: 'CSE',
    semester: 'S6',
    subject: 'Database Management Systems',
    academicYear: '2022-23',
    category: 'University Examination',
    examYear: 2023,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2023/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_qp_dbms_2023/view',
    fileName: 'KTU_DBMS_July2023_QP.pdf',
    fileSize: 1050000,
    downloadCount: 590,
    isPublished: true,
  },

  // Question Papers for Compiler Design (CSE S6)
  {
    title: '2025 KTU University Examination Question Paper',
    description: 'Official KTU question paper on Compiler Design CST304.',
    type: 'question-paper',
    department: 'CSE',
    semester: 'S6',
    subject: 'Compiler Design',
    academicYear: '2024-25',
    category: 'University Examination',
    examYear: 2025,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_qp_cd_2025/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_qp_cd_2025/view',
    fileName: 'KTU_CompilerDesign_June2025_QP.pdf',
    fileSize: 890000,
    downloadCount: 430,
    isPublished: true,
  },

  // Notes for Web Technology (IT S6)
  {
    title: 'Full Stack Web Architecture & React Handbook',
    description: 'Deep-dive into client-server protocols, asynchronous DOM, Node.js runtime, and component architectures.',
    type: 'notes',
    department: 'IT',
    semester: 'S6',
    subject: 'Web Technology',
    academicYear: '2026-27',
    category: 'Study Material',
    unitNumber: 1,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_it_webtech/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_it_webtech/view',
    fileName: 'IT_WebTechnology_FullGuide.pdf',
    fileSize: 4200000,
    downloadCount: 198,
    isPublished: true,
  },

  // Notes for Robot Kinematics (RAI S6)
  {
    title: 'Unit 1 & 2: DH Parameters & Robot Coordinate Systems',
    description: 'Rigorous derivation of rotation matrices, homogeneous transformations, and forward kinematics for multi-joint manipulators.',
    type: 'notes',
    department: 'RAI',
    semester: 'S6',
    subject: 'Robot Kinematics & Dynamics',
    academicYear: '2026-27',
    category: 'Unit Notes',
    unitNumber: 1,
    fileSource: 'external',
    fileUrl: 'https://drive.google.com/file/d/1sample_rai_kinematics/view',
    externalUrl: 'https://drive.google.com/file/d/1sample_rai_kinematics/view',
    fileName: 'RAI_Robotics_Kinematics_Notes.pdf',
    fileSize: 3800000,
    downloadCount: 275,
    isPublished: true,
  },
];

export const INITIAL_EVENTS = [
  {
    title: 'DHWANI 2026 — SFI GECI Annual Cultural Arts Fiesta',
    slug: 'dhwani-2026-annual-arts-fiesta',
    description:
      'The biggest cultural festival in the High Ranges of Idukki. A 3-day extravaganza of music, dance, theatre, literary battles, and solidarity, uniting thousands of engineering students from across Kerala.',
    posterUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80',
    eventDate: new Date('2026-11-15T09:30:00.000Z'),
    eventTime: '09:30 AM - 10:00 PM',
    venue: 'GEC Idukki Open Air Auditorium & Main Courtyard',
    category: 'Cultural',
    registrationUrl: 'https://dhwani.sfigeci.org',
    images: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    ],
    isPublished: true,
  },
  {
    title: 'ADVAITHA 2026 — National Level Technical Symposium & Hackathon',
    slug: 'advaitha-2026-technical-symposium',
    description:
      '36-hour flagship hackathon, robotics arena challenges, paper presentations, and tech talks from premier industry pioneers hosted by SFI GECI academic wing.',
    posterUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
    eventDate: new Date('2026-12-05T10:00:00.000Z'),
    eventTime: '10:00 AM Onwards',
    venue: 'Central Computing Facility & APJ Abdul Kalam Block',
    category: 'Technical',
    registrationUrl: 'https://advaitha.sfigeci.org',
    images: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    ],
    isPublished: true,
  },
  {
    title: 'Solidarity Blood Donation & Free Health Screening Camp',
    slug: 'solidarity-blood-donation-camp-2026',
    description:
      'Organized in collaboration with the District Medical Office and Government Medical College Idukki. Standing by the society with compassion and volunteer spirit.',
    posterUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=1200&q=80',
    eventDate: new Date('2026-10-20T09:00:00.000Z'),
    eventTime: '09:00 AM - 02:00 PM',
    venue: 'College Seminar Complex, Painavu',
    category: 'Social Welfare',
    registrationUrl: '',
    images: [],
    isPublished: true,
  },
  {
    title: 'Fresher Induction & Union Day Inauguration 2026',
    slug: 'fresher-induction-union-day-2026',
    description:
      'Welcoming the new batch of engineers to GEC Idukki. Inspiring sessions on student rights, progressive education, career roadmaps, and college life.',
    posterUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200&q=80',
    eventDate: new Date('2026-09-10T10:30:00.000Z'),
    eventTime: '10:30 AM',
    venue: 'College Main Auditorium',
    category: 'Academic',
    registrationUrl: '',
    images: [],
    isPublished: true,
  },
];

export const INITIAL_MEMBERS = [
  {
    name: 'Sidharth K. S.',
    position: 'President',
    department: 'CSE',
    semester: 'S7',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=80',
    bio: 'Dedicated to defending student rights, fostering academic excellence, and campus solidarity.',
    phone: '+91 94471 11223',
    email: 'president@sfigeci.org',
    order: 1,
    isActive: true,
  },
  {
    name: 'Ananya Ramesh',
    position: 'Secretary',
    department: 'ECE',
    semester: 'S7',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&q=80',
    bio: 'Championing inclusive education, campus safety, and progressive student union leadership.',
    phone: '+91 94472 22334',
    email: 'secretary@sfigeci.org',
    order: 2,
    isActive: true,
  },
  {
    name: 'Rahul Mohan',
    position: 'Vice President',
    department: 'ME',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80',
    bio: 'Spearheading campus infrastructure development, hostel amenities, and sports welfare.',
    phone: '+91 94473 33445',
    email: 'vp1@sfigeci.org',
    order: 3,
    isActive: true,
  },
  {
    name: 'Sneha K. P.',
    position: 'Vice President',
    department: 'EEE',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: '', // Demonstrates professional placeholder
    bio: 'Coordinating student welfare initiatives, library upgrades, and women safety forums.',
    phone: '',
    email: 'vp2@sfigeci.org',
    order: 4,
    isActive: true,
  },
  {
    name: 'Fathima Nizar',
    position: 'Joint Secretary',
    department: 'IT',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&q=80',
    bio: 'Active coordinator for women in engineering initiatives and grievance resolution.',
    phone: '',
    email: 'jointsec@sfigeci.org',
    order: 5,
    isActive: true,
  },
  {
    name: 'Vivek Raj',
    position: 'Joint Secretary',
    department: 'RAI',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: '', // Demonstrates professional placeholder
    bio: 'Facilitating technical seminars, peer mentoring, and lab infrastructure advocacy.',
    phone: '',
    email: 'jointsec2@sfigeci.org',
    order: 6,
    isActive: true,
  },
  {
    name: 'Arjun Vijayan',
    position: 'Secretariat Member',
    department: 'RAI',
    semester: 'S7',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&q=80',
    bio: 'Curating the digital notes repository, peer study circles, and KTU syllabus workshops.',
    phone: '',
    email: 'academic@sfigeci.org',
    order: 7,
    isActive: true,
  },
  {
    name: 'Devika Nair',
    position: 'Secretariat Member',
    department: 'EEE',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&q=80',
    bio: 'Passionate about creative expression, student journalism, and political literature.',
    phone: '',
    email: 'editor@sfigeci.org',
    order: 8,
    isActive: true,
  },
  {
    name: 'Mohammed Aslam',
    position: 'Secretariat Member',
    department: 'CSE',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&q=80',
    bio: 'Leading open source student tech initiatives and coding clubs.',
    phone: '',
    order: 9,
    isActive: true,
  },
  {
    name: 'Pooja S. Kumar',
    position: 'Secretariat Member',
    department: 'ECE',
    semester: 'S5',
    academicYear: '2026-27',
    photoUrl: '', // Demonstrates professional placeholder
    bio: 'Active member organizing cultural festivals and social awareness rallies.',
    phone: '',
    order: 10,
    isActive: true,
  },
  {
    name: 'Akhil B. Chandran',
    position: 'Secretariat Member',
    department: 'ME',
    semester: 'S7',
    academicYear: '2026-27',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&q=80',
    bio: 'Hostel committee secretary and student union organizer.',
    phone: '',
    order: 11,
    isActive: true,
  },
  {
    name: 'Nandana Suresh',
    position: 'Unit Member',
    department: 'CSE',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 12,
    isActive: true,
  },
  {
    name: 'Midhun Joy',
    position: 'Unit Member',
    department: 'IT',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 13,
    isActive: true,
  },
  {
    name: 'Gopika R.',
    position: 'Unit Member',
    department: 'ECE',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 14,
    isActive: true,
  },
  {
    name: 'Abhishek V.',
    position: 'Unit Member',
    department: 'ME',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 15,
    isActive: true,
  },
  {
    name: 'Anjali Thomas',
    position: 'Unit Member',
    department: 'EEE',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 16,
    isActive: true,
  },
  {
    name: 'Kiran Pradeep',
    position: 'Unit Member',
    department: 'RAI',
    semester: 'S3',
    academicYear: '2026-27',
    photoUrl: '',
    order: 17,
    isActive: true,
  },

  // 2025-26 Batch
  {
    name: 'Gautham Krishna',
    position: 'President',
    department: 'CSE',
    semester: 'Alumni',
    academicYear: '2025-26',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&q=80',
    bio: 'Led the historic campaign for high-speed campus fiber Wi-Fi and girls hostel expansion.',
    phone: '+91 94471 99881',
    order: 1,
    isActive: true,
  },
  {
    name: 'Aiswarya Lakshmi',
    position: 'Secretary',
    department: 'EEE',
    semester: 'Alumni',
    academicYear: '2025-26',
    photoUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=500&q=80',
    bio: 'Excellence awardee for inter-college union activities and social aid drives in Idukki.',
    phone: '+91 94472 99882',
    order: 2,
    isActive: true,
  },
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    title: 'KTU S6 & S4 B.Tech End-Semester Examination Timetable Published',
    shortDescription: 'APJ Abdul Kalam Technological University has released the official schedule for upcoming semester exams.',
    content:
      'Students are advised to review the subject-wise exam dates carefully on the KTU portal. Hall tickets will be issued from the department offices next Monday. SFI GECI notes repository has been fully refreshed with unit-wise revision materials and 5-year question papers.',
    priority: 'urgent',
    publishedAt: new Date(),
    isPublished: true,
  },
  {
    title: 'GECI College Bus Route No. 4 Thodupuzha–Painavu Resumes',
    shortDescription: 'Following representation from SFI Unit, the college transport committee has resolved bus timings.',
    content:
      'Morning pickup will be at 07:15 AM from Thodupuzha KSRTC Terminal. Evening return leaves college campus at 04:45 PM. Students requiring pass renewal may contact student union transport representatives.',
    priority: 'important',
    publishedAt: new Date(Date.now() - 86400000 * 2),
    isPublished: true,
  },
  {
    title: 'Digital Library & IEEE Xplore 24/7 Access Extended to Hostels',
    shortDescription: 'High-speed remote institutional proxy setup completed successfully.',
    content:
      'All GECI engineering students can now access IEEE research papers, ScienceDirect, and digital books from college hostels using their college LDAP credentials.',
    priority: 'normal',
    publishedAt: new Date(Date.now() - 86400000 * 5),
    isPublished: true,
  },
];

export const INITIAL_GALLERY = [
  {
    title: 'Union Day & Cultural Inauguration',
    description: 'Electrifying moments from the SFI GECI Union Day celebrations at the campus amphitheatre.',
    date: new Date('2026-08-22'),
    coverImageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1000&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80', caption: 'Inaugural lighting ceremony' },
      { url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80', caption: 'Student gathering in solidarity' },
      { url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80', caption: 'Musical extravaganza by college band' },
    ],
    isPublished: true,
  },
  {
    title: 'Campus Greenery & High-Range Cleanliness Drive',
    description: 'SFI GECI volunteers planting native saplings and cleaning the serene Painavu hill campus.',
    date: new Date('2026-06-05'),
    coverImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1000&q=80',
    images: [
      { url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80', caption: 'Environment day sapling planting' },
      { url: 'https://images.unsplash.com/photo-1516214104703-d870798883c5?w=800&q=80', caption: 'Eco-warriors at GEC Idukki' },
    ],
    isPublished: true,
  },
];

export const INITIAL_COMPLAINT_CATEGORIES = [
  { name: 'Academic', description: 'Curriculum, internal marks, lab facilities, syllabus coverage' },
  { name: 'Campus Facilities', description: 'Classroom amenities, water supply, restrooms, electricity' },
  { name: 'Hostel', description: 'Hostel rooms, mess food quality, security, curfew issues' },
  { name: 'Canteen', description: 'Campus canteen hygiene, pricing, meal variety' },
  { name: 'Transportation', description: 'College buses, KSRTC services, pass renewals, schedules' },
  { name: 'Library', description: 'Book availability, digital access, reading room timings' },
  { name: 'Examination', description: 'KTU exam registration, hall tickets, revaluation queries' },
  { name: 'Student Activities', description: 'Sports facilities, gym, club rooms, festival permissions' },
  { name: 'Harassment / Safety', description: 'Ragging complaints, gender safety, campus security' },
  { name: 'Administration', description: 'Office certificates, scholarships, fee concession processing' },
  { name: 'Other', description: 'General grievances and suggestions' },
];

export const INITIAL_COMPLAINTS = [
  {
    complaintNumber: 'SFI-2026-00101',
    studentName: 'Akhil K. B.',
    email: 'akhil.kb@gecidukki.ac.in',
    department: 'CSE',
    semester: 'S6',
    category: 'Campus Facilities',
    subject: 'Issue with projector in CS Seminar Hall 2',
    description: 'The overhead HDMI projector flickers continuously during technical seminars and presentations.',
    attachmentUrl: '',
    isAnonymous: false,
    status: 'In Progress',
    priority: 'Medium',
    assignedTo: 'Rahul Mohan (VP)',
    internalNotes: [
      { note: 'Inspected with lab technician. New HDMI cable ordered.', author: 'Rahul Mohan', createdAt: new Date() }
    ],
    statusHistory: [
      { status: 'Submitted', comment: 'Complaint lodged by student', changedBy: 'System', changedAt: new Date(Date.now() - 86400000 * 3) },
      { status: 'Under Review', comment: 'Assigned to infrastructure convenor', changedBy: 'Admin', changedAt: new Date(Date.now() - 86400000 * 2) },
      { status: 'In Progress', comment: 'Technician inspection completed', changedBy: 'Admin', changedAt: new Date(Date.now() - 86400000 * 1) },
    ],
  },
  {
    complaintNumber: 'SFI-2026-00102',
    studentName: 'Anonymous Student',
    email: '',
    department: 'EEE',
    semester: 'S4',
    category: 'Canteen',
    subject: 'Request for extended evening tea & snack timings',
    description: 'Hostellers staying back for lab work find the canteen closed by 4:30 PM. Requesting extension till 6:00 PM.',
    attachmentUrl: '',
    isAnonymous: true,
    status: 'Resolved',
    priority: 'Low',
    assignedTo: 'Ananya Ramesh',
    internalNotes: [
      { note: 'Discussed with canteen vendor and principal. Extended till 5:45 PM.', author: 'Ananya Ramesh', createdAt: new Date() }
    ],
    statusHistory: [
      { status: 'Submitted', comment: 'Received from anonymous student', changedBy: 'System', changedAt: new Date(Date.now() - 86400000 * 7) },
      { status: 'Resolved', comment: 'Canteen vendor agreed to keep tea counters open till 5:45 PM', changedBy: 'Admin', changedAt: new Date(Date.now() - 86400000 * 1) },
    ],
  },
];
